version: '3.8'

services:
  app:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    environment:
      - PHOTOPRISM_ADMIN_USER
      - PHOTOPRISM_ADMIN_PASSWORD
      - PHOTOPRISM_AUTH_MODE=password
      - PHOTOPRISM_SITE_URL
      - PHOTOPRISM_ORIGINALS_LIMIT
      - PHOTOPRISM_HTTP_COMPRESSION=gzip
      - PHOTOPRISM_LOG_LEVEL=warning
      - PHOTOPRISM_READONLY
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_SERVER=db:3306
      - PHOTOPRISM_DATABASE_NAME=photoprism
      - PHOTOPRISM_DATABASE_USER=photoprism
      - PHOTOPRISM_DATABASE_PASSWORD=photoprism
      - PHOTOPRISM_SITE_CAPTION
      - PHOTOPRISM_SITE_DESCRIPTION
      - PHOTOPRISM_SITE_AUTHOR
      - PHOTOPRISM_WORKERS
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    working_dir: "/photoprism"
    depends_on:
      - db
    volumes:
      - app_data:/photoprism/storage
      - app_originals:/photoprism/originals
      - app_import:/photoprism/import
    networks:
      app_db:
      proxy_apps:
    cpus: 1.0
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.photoprismimportcron.schedule: "@every 25m"
      ofelia.job-exec.photoprismimportcron.command: "photoprism import /photoprism/import"
      ofelia.job-exec.photoprismindexcron.schedule: "@every 3h"
      ofelia.job-exec.photoprismindexcron.command: "photoprism index --cleanup"
  db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=photoprism
      - MARIADB_USER=photoprism
      - MARIADB_PASSWORD=photoprism
      - MARIADB_ROOT_PASSWORD=photoprism
    networks:
      app_db:
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.photoprismdbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.photoprismdbbackup.command: "sh -c 'mariadb-dump --user=photoprism --password=photoprism photoprism > /var/lib/mysql/backup.sql'"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
  sftp:
    image: ghcr.io/hueske-digital/sftp:latest
    restart: unless-stopped
    volumes:
      - sftp_keys:/etc/ssh
      - app_import:/home/${SFTP_USERNAME}/import
      - $PWD/publickeys:/home/${SFTP_USERNAME}/.ssh/keys:ro
    ports:
      - "2223:22"
    networks:
      default:
    # Empty password = only allow publickeys
    command: ${SFTP_USERNAME}:${SFTP_PASSWORD}:1000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536


volumes:
  app_data:
  app_originals:
  app_import:
  db_data:
  sftp_keys:

networks:
  app_db:
  proxy_apps:
    name: proxy_apps
    external: true
